### ISSUE TITLE
I was adding my classes on the site when I accidentally added the wrong class, but now I can't take it off of my list of classes. I can't find any button or setting, so either a button or just information how to take incorrect classes off would be nice.

### ISSUE THREAD

**Issue by gdgc5nm** [deltasig/sphinx#56]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

## Regarding Approval

Features are handled differently than bugs.  Where bugs are handled much more quickly (depending on severity), features take longer and are far more numerous.  Therefore, in order for feature requests to be considered, the following will need to happen before work begins:

- Sufficient dialog will need to occur in order to define requirements
- 5 or more "thumbs up" 👍 reactions on your original post from other members, and less than 5 "thumbs down" 👎 reactions.

**Comment by tymorrow** [comment]
Hi Garrett,

Since this is dis-enrollment-related, the current Academic Chairman is who you need to talk to.
This is per the Wiki, which is linked on the left sidebar of the website under "Website."
https://github.com/deltasig/sphinx/wiki/academic-chairman

In case they weren't trained by the previous Academic Chairman, they can do this by going to:
Roster -> clicking on you -> clicking the "All classes" link on top-right of your classes list -> clicking/confirming delete on the class.

I would also kindly ask that you please fill out issues properly in the future instead of dumping the problem into the title.
